config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'flights/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "flights#index"
  resources :flights, only: [:index]
  resources :bookings, only: [:new,:create,:show]
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name:"Flight", foreign_key:"departure_airport_id"
    has_many :arriving_flights, class_name:"Flight", foreign_key:"arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: 'Airport'
    belongs_to :arrival_airport, class_name: 'Airport'

    has_many :bookings
    has_many :passengers, through: :bookings
    
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new(flight_id: @flight.id)
    @num_passengers = params[:passengers].to_i

    #build passengers according to num_passengers
    @passengers = @num_passengers.times { @booking.passengers.build }
    # debugger
     # Build additional fields for each passenger
    # @booking.passengers.each do |passenger|
    #   passenger.build_user_credentials
    # end

  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    
    if @booking.save
      @booking.passengers.each { |passenger| PassengerMailer.with(passenger: passenger).confirm_email.deliver_later }
      redirect_to booking_path(@booking)
    else
      @flight = Flight.find(params[:booking][:flight_id])
      render :new
    end

  end


  private
  def booking_params 
    params.require(:booking).permit(:flight_id,passengers_attributes: [:id,  :name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @departure_airports = Airport.all
    @arrival_airports = Airport.all
    @passengers = 1..4
    @flight_dates = Flight.pluck(:start_datetime).map { |date| date.to_date }.uniq 
    
    if params[:departure_airport_id]
      @flights = Flight.where(
        departure_airport_id: params[:departure_airport_id].to_i,
        arrival_airport_id: params[:arrival_airport_id].to_i,
        start_datetime: Date.parse(params[:start_datetime]).all_day
      )

      # debugger
    end

    # private

    # def flight_params
    #   params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :start_datetime)
    # end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h2>Booking Page</h2>

Flight From <%= @flight.departure_airport.code %> to <%= @flight.arrival_airport.code %> <br>
Date <%= @flight.start_datetime.strftime("%d %b, %Y") %> <br>
Flight ID <%= @flight.id %>

<h3>Personal Information</h3>

<%= form_for @booking do |f| %>
  <%= f.hidden_field :flight_id %>

  <% @num_passengers.times do |index| %>
    <% passenger = @booking.passengers[index] %>
    <%= f.fields_for :passengers, passenger do |passenger_fields| %>
      <div class="passenger-fields">
        <%= passenger_fields.label :name, "Passenger#{index + 1} Name: " %>
        <%= passenger_fields.text_field :name %>

        <%= passenger_fields.label :email, "Passenger#{index + 1} Email: " %>
        <%= passenger_fields.text_field :email %>
      </div>
    <% end %>
    <br><br> <!-- Add spacing between each passenger's fields -->
  <% end %>

  <%= f.submit "Create Booking" %>
<% end %>

app/views/bookings/show.html.erb
<h2>Booking Details</h2>

<p><strong>Flight:</strong> <%= @booking.flight.departure_airport.code %> to <%= @booking.flight.arrival_airport.code %></p>
<p><strong>Date:</strong> <%= @booking.flight.start_datetime.strftime("%d %b, %Y") %></p>
<p><strong>Flight ID:</strong> <%= @booking.flight.id %></p>

<h3>Passengers</h3>

<% @booking.passengers.each do |passenger| %>
  <div class="passenger-details">
    <p><strong>Name:</strong> <%= passenger.name %></p>
    <p><strong>Email:</strong> <%= passenger.email %></p>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/flights/index.html.erb
<h1>Flights Search</h1>

<%= form_with url: flights_path, method: :get, local: true do |form| %>
  <%= form.label :departure_airport_id, 'Departure Airport' %>
  <%= form.select :departure_airport_id, @departure_airports.map { |airport| [airport.code, airport.id] }, { include_blank: true }, { class: 'form-control' } %>
    <br><br>
  <%= form.label :arrival_airport_id, 'Arrival Airport' %>
  <%= form.select :arrival_airport_id, @arrival_airports.map { |airport| [airport.code, airport.id] }, { include_blank: true }, { class: 'form-control' } %>
    <br><br>
  <%= form.label :start_datetime, 'Flight Date' %>
  <%= form.select :start_datetime, @flight_dates %>
    <br><br>
  <%= form.label :passengers, 'Number of Passengers' %>
  <%= form.select :passengers, @passengers, { class: 'form-control' } %>
<br><br>
  <%= form.submit 'Search', class: 'btn btn-primary' %>
<% end %>

<% if @flights.present? %>
  <hr>
  <h3>Select a Flight: </h3>    
  <%= form_with url: new_booking_path, method: :get, local:true do |form| %>
    <%= form.hidden_field :passengers, value: params[:passengers] %>
    <% @flights.each do |flight|%>
        <%= form.radio_button :flight_id, flight.id %> 
        <%= form.label :flight_id, flight.start_datetime.strftime("%H:%M")%>            
    <% end %>

    <br><br>
    <%= form.submit "Next"%>
  <% end %>

<% else %>
    <hr>
    <p>No Flights Found</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>